"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeWheel = exports.Store = exports.EventEmitter = exports.getUUID = exports.throttle = exports.debounce = exports.addHint = exports.isWebpSupport = exports.isWebGLAvailable = exports.isTouch = exports.isIE = exports.randomInteger = exports.randomSort = exports.even = exports.Share = exports.Performance = exports.base64ToArrayBuffer = exports.hexToRgb = exports.lerpLimit = exports.lerp = exports.formatDate = exports.queryParse = exports.mapObjectToParamsString = exports.http = exports.History = exports.ease = exports.moveElements = exports.clearElements = exports.prefixedCSSValue = exports.getCSS = exports.deleteCookie = exports.setCookie = exports.getCookie = exports.CanvasRenderer = exports.fancyTime = exports.declension = void 0;
var declension_1 = require("./beautify/declension");
Object.defineProperty(exports, "declension", { enumerable: true, get: function () { return declension_1.declension; } });
var time_1 = require("./beautify/time");
Object.defineProperty(exports, "fancyTime", { enumerable: true, get: function () { return time_1.fancyTime; } });
var CanvasRenderer_1 = require("./canvas/CanvasRenderer");
Object.defineProperty(exports, "CanvasRenderer", { enumerable: true, get: function () { return CanvasRenderer_1.CanvasRenderer; } });
var cookie_1 = require("./cookie/cookie");
Object.defineProperty(exports, "getCookie", { enumerable: true, get: function () { return cookie_1.getCookie; } });
Object.defineProperty(exports, "setCookie", { enumerable: true, get: function () { return cookie_1.setCookie; } });
Object.defineProperty(exports, "deleteCookie", { enumerable: true, get: function () { return cookie_1.deleteCookie; } });
var css_1 = require("./css/css");
Object.defineProperty(exports, "getCSS", { enumerable: true, get: function () { return css_1.getCSS; } });
Object.defineProperty(exports, "prefixedCSSValue", { enumerable: true, get: function () { return css_1.prefixedCSSValue; } });
var dom_1 = require("./DOM/dom");
Object.defineProperty(exports, "clearElements", { enumerable: true, get: function () { return dom_1.clearElements; } });
Object.defineProperty(exports, "moveElements", { enumerable: true, get: function () { return dom_1.moveElements; } });
var easings_1 = require("./easings/easings");
Object.defineProperty(exports, "ease", { enumerable: true, get: function () { return easings_1.ease; } });
var History_1 = require("./history/History");
Object.defineProperty(exports, "History", { enumerable: true, get: function () { return History_1.History; } });
var http_1 = require("./http/http");
Object.defineProperty(exports, "http", { enumerable: true, get: function () { return http_1.http; } });
var mapObjectToParamsString_1 = require("./http/mapObjectToParamsString");
Object.defineProperty(exports, "mapObjectToParamsString", { enumerable: true, get: function () { return mapObjectToParamsString_1.mapObjectToParamsString; } });
var queryParse_1 = require("./http/queryParse");
Object.defineProperty(exports, "queryParse", { enumerable: true, get: function () { return queryParse_1.queryParse; } });
var formatDate_1 = require("./number/formatDate");
Object.defineProperty(exports, "formatDate", { enumerable: true, get: function () { return formatDate_1.formatDate; } });
var number_1 = require("./number/number");
Object.defineProperty(exports, "lerp", { enumerable: true, get: function () { return number_1.lerp; } });
Object.defineProperty(exports, "lerpLimit", { enumerable: true, get: function () { return number_1.lerpLimit; } });
Object.defineProperty(exports, "hexToRgb", { enumerable: true, get: function () { return number_1.hexToRgb; } });
Object.defineProperty(exports, "base64ToArrayBuffer", { enumerable: true, get: function () { return number_1.base64ToArrayBuffer; } });
var Performance_1 = require("./performance/Performance");
Object.defineProperty(exports, "Performance", { enumerable: true, get: function () { return Performance_1.Performance; } });
var share_1 = require("./share/share");
Object.defineProperty(exports, "Share", { enumerable: true, get: function () { return share_1.Share; } });
var sort_1 = require("./sort/sort");
Object.defineProperty(exports, "even", { enumerable: true, get: function () { return sort_1.even; } });
Object.defineProperty(exports, "randomSort", { enumerable: true, get: function () { return sort_1.randomSort; } });
Object.defineProperty(exports, "randomInteger", { enumerable: true, get: function () { return sort_1.randomInteger; } });
var test_1 = require("./test/test");
Object.defineProperty(exports, "isIE", { enumerable: true, get: function () { return test_1.isIE; } });
Object.defineProperty(exports, "isTouch", { enumerable: true, get: function () { return test_1.isTouch; } });
Object.defineProperty(exports, "isWebGLAvailable", { enumerable: true, get: function () { return test_1.isWebGLAvailable; } });
Object.defineProperty(exports, "isWebpSupport", { enumerable: true, get: function () { return test_1.isWebpSupport; } });
var addHint_1 = require("./utilities/addHint");
Object.defineProperty(exports, "addHint", { enumerable: true, get: function () { return addHint_1.addHint; } });
var debounce_1 = require("./utilities/debounce");
Object.defineProperty(exports, "debounce", { enumerable: true, get: function () { return debounce_1.debounce; } });
var throttle_1 = require("./utilities/throttle");
Object.defineProperty(exports, "throttle", { enumerable: true, get: function () { return throttle_1.throttle; } });
var uuid_1 = require("./utilities/uuid");
Object.defineProperty(exports, "getUUID", { enumerable: true, get: function () { return uuid_1.getUUID; } });
var EventEmitter_1 = require("./EventEmitter");
Object.defineProperty(exports, "EventEmitter", { enumerable: true, get: function () { return EventEmitter_1.EventEmitter; } });
var Store_1 = require("./Store");
Object.defineProperty(exports, "Store", { enumerable: true, get: function () { return Store_1.Store; } });
var normalizeWheel_1 = require("./wheel/normalizeWheel");
Object.defineProperty(exports, "normalizeWheel", { enumerable: true, get: function () { return normalizeWheel_1.normalizeWheel; } });
